version: "3.7"

services:

  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1450:1433
    environment:
      - SA_PASSWORD=2Secure*Password2
      - ACCEPT_EULA=Y

  todo-app-backend:
    image: todo-app-backend
    ports:
    - 5025:5025
    environment:
    - ASPNETCORE_URLS=http://0.0.0.0:5025
    - ASPNETCORE_ENVIRONMENT=Development
    - DefaultConnection=Initial Catalog=MyDockerToDoDb; Data Source=ms-sql-server,1450; Persist Security Info=True;User ID=SA;Password= 2Secure*Password2
    build:
        context: .
        dockerfile: Dockerfile
    container_name: todo-app-backend
    depends_on:
    - ms-sql-server

  # todo-app-frontend:
  #   image: todo-app-frontend
  #   ports:
  #   - 8080:8080
  #   build:
  #       context: .
  #       dockerfile: ../../todoapp-frontend/Dockerfile
  #   container_name: todo-app-backend
  #   depends_on:
  #   - ms-sql-server
  #   - todo-app-backend