version: "3.7"

services:

  sql-server-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - SA_PASSWORD=Password1!
      - ACCEPT_EULA=Y

  todo-app-backend:
    image: todo-app-backend
    ports:
    - 5025:5025
    environment:
    - ASPNETCORE_URLS=http://0.0.0.0:5025
    - DefaultConnection=Server=sql-server-db;Database=MyDockerToDoDb;User Id=sa;Password=Password1!;
    build:
        context: .
        dockerfile: Dockerfile
    container_name: todo-app-backend
    depends_on:
    - sql-server-db

  # todo-frontend-app:
  #   image: todo-frontend-app
  #   build:
  #     context: .
  #     dockerfile: todoapp-frontend/Dockerfile
  #   depends_on:
  #     - sql-server-db
  #     - backend-app
